### ISSUE TITLE
Support centering by flexbox

### ISSUE THREAD

**Issue by cvan** [oliverzheng/howtocenterincss#16]
example: http://philipwalton.github.io/solved-by-flexbox/demos/vertical-centering/

**Comment by thijsBreker** [comment]
Or any of the other techniques used in this jsbin: https://jsbin.com/honawo/

**Comment by pajtai** [comment]
:+1: super useful in modern / modernish browsers

http://caniuse.com/#feat=flexbox

**Comment by cmwwebfx** [comment]
+1 on this please

**Comment by oliverzheng** [comment]
Gonna add a browser & browser-version selection, so that if only modern browsers are to be used, flexbox will be selected.

**Comment by Schweinepriester** [comment]
+1

maybe flex should even become the default

**Comment by cvan** [comment]
I would recommend also including the legacy flexbox rules generated by autoprefixer

**Comment by oliverzheng** [comment]
This is in as of e20016b.

I haven't found an example of how to use flexbox and maintain compatibility with IE10, since it uses the legacy flexbox syntax. @cvan, how does autoprefixer fix that?
