### ISSUE TITLE
it is doesn't work

### ISSUE THREAD

**Issue by mishanon** [oliverzheng/howtocenterincss#18]
it is should align Center and Middle

![issue](https://cloud.githubusercontent.com/assets/1140003/7319580/9db5fa84-eaa7-11e4-8feb-176bdb11848b.png)

but on screen, align is Top and Right. it is wrong

**Comment by oliverzheng** [comment]
Yeah this wasn't thoroughly tested. Gonna create some webdriver tests to go through all of them across browsers/platforms. Thanks for reporting!

**Comment by oliverzheng** [comment]
Same as #17.
