### ISSUE TITLE
checkout absolute positioning

### ISSUE THREAD

**Issue by githubissue** [oliverzheng/howtocenterincss#23]
@oliverzheng filed this issue from https://twitter.com/oliverzheng/status/593185481958952960

**Comment by shshaw** [comment]
Concerning `position: absolute` and centering:

If width/height of the `position: absolute` element are set (percentage, pixels, or any unit), then it's as simple as:

```css
.absolute-center {
  position: absolute;
  top: 0; left: 0; bottom: 0; right: 0;
  margin: auto;
}
```
You can fine tune the positioning of the element using the appropriate margin: `margin-right: 0` will align the item on the right side, or `margin-bottom: 0` for bottom alignment. You can also offset the bounds of where the item is centered by adjusting the `top`, `left`, `bottom` or `right` values. I cover this all more in-depth here: http://www.smashingmagazine.com/2013/08/09/absolute-horizontal-vertical-centering-css/

Alternatively, dimensions are not needed if you aren't going to horizontally or vertically center a `position: absolute`. Aligning bottom right would simply be `position: absolute; bottom: 0; right: 0;`, and the bounding box is fit to the content.

Some other methods for centering (flexbox, table-cell, transforms) are covered in the article, and the CSS Tricks article is helpful as well: https://css-tricks.com/centering-css-complete-guide/

**Comment by oliverzheng** [comment]
Nice. I'm in the process of setting up some visual snapshot tests to get all the methods tested across browsers and devices, but this sounds pretty clean for IE8-10. I'll add this in. Thanks!
