### ISSUE TITLE
Add warning about -webkit- CSS prefixes

### ISSUE THREAD

**Issue by alfredobarron** [oliverzheng/howtocenterincss#34]

**Comment by oliverzheng** [comment]
What's not found in safari? Url? Screenshot?

**Comment by alfredobarron** [comment]
initial loading


http://alfredobarron.com/


![captura de pantalla 2015-06-16 a las 12 53 40](https://cloud.githubusercontent.com/assets/2327016/8190195/d083e2de-1426-11e5-9389-ae3f10a049cf.png)

thanks.

**Comment by oliverzheng** [comment]
I don't understand. What isn't found? Isn't that your website?

**Comment by alfredobarron** [comment]
no center loading in safari
![captura de pantalla 2015-06-16 a las 12 53 40](https://cloud.githubusercontent.com/assets/2327016/8190337/948248b0-1427-11e5-8496-a9324b56ee10.png)

**Comment by alfredobarron** [comment]
http://codepen.io/alfredobarron/pen/EjvRbM

**Comment by oliverzheng** [comment]
Add -webkit- prefix to flex.

I'll add a warning about this in the code generated section.

**Comment by alfredobarron** [comment]
Sorry I did not know this property, thanks good work

**Comment by alfredobarron** [comment]
can you help me http://codepen.io/alfredobarron/pen/EjvRbM

**Comment by oliverzheng** [comment]
I'm keeping this open to track adding the "-webkit" notice.
