### ISSUE TITLE
Suggestion for the site

### ISSUE THREAD

**Issue by Toltar** [oliverzheng/howtocenterincss#36]
I would like to suggest having a clear all or a clear button on each section. Possibly could be a nice feature. I will fork it if you'd like for me to implement that feature to the site. It would be nice to have something for the user to clear their input since there is a lot of input. Also have you considered doing it in AngularJS to implement a live generation as the user inputs things. No issues with your site though just ideas. :D :+1:

**Comment by oliverzheng** [comment]
What's the scenario of having a clear button?

It's in React.js and can already live generate based on user input. The thing is all the inputs need to be specified before anything can be generated, so it'd just be empty the whole time until all the inputs are specified, and when the last one is, it won't be apparent to the user that it updated.
