### ISSUE TITLE
Generate code button does nothing

### ISSUE THREAD

**Issue by COLABORATI** [oliverzheng/howtocenterincss#40]
I just tried your nice site, unfortunately the generate code button does not do anything. No code generated, no error message, nothing.

**Comment by oliverzheng** [comment]
Did you select all the required input options? Can you paste a screenshot of the page?

**Comment by tjsreece** [comment]
Same for me, using Chrome Version 50.0.2633.3 dev-m (64-bit). Even tried it on IE 11. My OS is Windows 8.1 x64. 

[Heres a screenshot](http://i.imgur.com/oyeyu1L.png)

**Comment by oliverzheng** [comment]
@tjsreece you need to select the vertical alignment.

This site really needs some kind of error box to alert the user when something is missing. I don't have time at the moment. Does someone want to take a look?

**Comment by tjsreece** [comment]
I would submit a pull request but I don't know react.js very well. I will look into it though and see what I can do.

**Comment by darkmorpher** [comment]
@oliverzheng

Simple solution would be to mention that both values are required under _Alignment_

**Comment by oliverzheng** [comment]
@darkmorpher good idea. Want to submit a pull request? :)

**Comment by oliverzheng** [comment]
5df0fd2 should address this.
