### ISSUE TITLE
Usage of centering inside CSS Grid Layout

### ISSUE THREAD

**Issue by fdenzer** [oliverzheng/howtocenterincss#42]
I might like to specify the width/height of my `div`s i.e. rows, in fractions.
Is `display: grid;` _compatible_ with the flexbox rules proposed by the generator?
Is that a _good_ solution?

**Comment by oliverzheng** [comment]
Are you trying to specify the width/height of what you want to center (content) or its container (parent)? Grid layout should be compatible with flex box, in the sense that a grid's cell (child of the grid) can align its own children with flexbox, making it a parent of content.

**Comment by fdenzer** [comment]
The content width is a percentage of parent, due to grid rules.

But if it's compatible (yet redundant?) you may consider my question withdrawn ☺
