### ISSUE TITLE
Feature Request: a Visual Studio Code extension!

### ISSUE THREAD

**Issue by mrjones2014** [oliverzheng/howtocenterincss#45]
This would be AWESOME as a Visual Studio Code extension. Perhaps it could even scan the markup in your current file somehow and automatically set the parameters from your current markup?

**Comment by oliverzheng** [comment]
I doubt this would ever be feasible. It wouldn't just be the markup it needs to scan, but any CSS that would be applied to the markup at runtime, which may not be known during development.
