### ISSUE TITLE
Recommends auto margin method for a div of unkown width

### ISSUE THREAD

**Issue by mangelozzi** [oliverzheng/howtocenterincss#46]
The **auto margin** method to centre horizontally can only be used on divs of known width. This website incorrectly recommends it for divs of unknown width. The generated code does not work.

**Comment by oliverzheng** [comment]
Can you post the link to the howtocenterincss page? That'll have all the options.

**Comment by mangelozzi** [comment]
http://howtocenterincss.com/#contentType=div&horizontal=center&vertical=top
Generates this code:
```
<div>
  <div style="margin-left:auto;margin-right:auto;">HELLO</div>
</div>
```
Which will not center "HELLO" text.

**Comment by oliverzheng** [comment]
`Div` is selected under Content, so it won't try to center text. If you select `Text` under Content, it'll generate

```
<div style="text-align:center;">Text Content</div>
```

**Comment by mangelozzi** [comment]
Sorry my mistake, I assumed the inner div width was its content width, but it was much wider making it appear left aligned (was the text left aligned in a center aligned div).
Thank you!
